apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: k8dynamos.storm.com
spec:
  group: storm.com
  version: v1
  names:
    kind: K8dynamo
    singular: k8dynamo
    plural: k8dynamos
    shortNames:
    - kd
  scope: Namespaced
  validation:
    openAPIV3Schema:
      type: object
      properties:
        spec:
          type: object
          properties:
            tableName:
              type: string
            readUnit:
              type: integer
              minimum: 1
              maximum: 5
            writeUnit:
              type: integer
              minimum: 1
              maximum: 5
  
